// src/app/layout.tsx
'use client';

import './globals.css';
import 'bootstrap/dist/js/bootstrap.bundle.min';

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
